UNITS = [
    ("bytes-to-rows", "Bytes to rows", "See how a database turns raw storage into records.", "▦", [
        ("latency-ladder", "The latency ladder", "Why every database is a bet on the memory hierarchy", 8),
        ("pages-and-blocks", "Pages & blocks", "The fundamental unit of database I/O", 10),
        ("anatomy-of-a-row", "Anatomy of a row", "Headers, nulls, alignment, and variable data", 10),
        ("slotted-pages", "Slotted pages", "Keep record identifiers stable while rows move", 12),
        ("heap-files", "Heap files", "Find space and scan unordered tables", 10),
        ("page-surgeon", "Lab: Page Surgeon", "Pack, update, and compact a real page model", 15),
        ("bytes-checkpoint", "Checkpoint", "Prove you can reason from bytes to rows", 12),
    ]),
    ("indexes", "Indexes that scale", "Navigate terabytes with trees and write-optimized structures.", "⌘", [
        ("sorted-access", "Sorted access", "Trade write work for faster lookup", 8), ("btree-anatomy", "B+ tree anatomy", "Fanout, height, leaves, and separators", 10), ("btree-search", "Tree search", "Trace a lookup from root to record", 10), ("splits-merges", "Splits & merges", "Keep the tree balanced under mutation", 12), ("clustered-indexes", "Clustered indexes", "Understand primary and secondary lookup paths", 10), ("lsm-trees", "LSM trees", "Turn random writes into sequential runs", 12), ("bloom-filters", "Bloom filters", "Skip impossible reads probabilistically", 10), ("index-checkpoint", "Checkpoint", "Choose and operate the right index", 12)
    ]),
    ("buffer-pool", "Memory is the database", "Manage scarce memory, locality, and dirty state.", "◫", [("locality", "Locality", "Why nearby and recent access matters", 8), ("buffer-pool-basics", "Buffer pool", "Map disk pages into memory frames", 10), ("pin-dirty", "Pin & dirty", "Coordinate safe access and persistence", 10), ("replacement", "Replacement", "LRU, CLOCK, and workload resistance", 12), ("prefetch", "Prefetch", "Read tomorrow's pages today", 10), ("eviction-lab", "Lab: Eviction Arena", "Run policies against live workloads", 15), ("memory-checkpoint", "Checkpoint", "Control the memory hierarchy", 12)]),
    ("execution", "Executing a query", "Build relational results one operator at a time.", "▶", [("execution-models", "Execution models", "Iterator, vectorized, and compiled execution", 10), ("scans", "Scans", "Sequential, index, and bitmap access", 10), ("external-sort", "External sort", "Sort data larger than memory", 12), ("hash-join", "Hash join", "Partition and probe efficiently", 12), ("merge-join", "Merge join", "Exploit ordered inputs", 10), ("nested-loops", "Nested loops", "Make the simple join fast", 10), ("aggregation", "Aggregation", "Hash and streaming groups", 10), ("execution-checkpoint", "Checkpoint", "Trace physical query execution", 12)]),
    ("planning", "Planning a query", "Estimate costs and search an enormous plan space.", "⌁", [("statistics", "Statistics", "Summarize distributions compactly", 10), ("cardinality", "Cardinality estimation", "Predict rows through operators", 12), ("cost-models", "Cost models", "Compare I/O, CPU, and memory", 10), ("join-order", "Join ordering", "Search combinatorial alternatives", 12), ("plan-instability", "Plan instability", "Diagnose estimates at the tipping point", 10), ("plan-lab", "Lab: Plan Detective", "Repair a pathological plan", 15), ("planning-checkpoint", "Checkpoint", "Think like an optimizer", 12)]),
    ("mvcc", "Transactions & MVCC", "Give concurrent users coherent versions of reality.", "◉", [("acid", "ACID, precisely", "Replace slogans with mechanisms", 10), ("schedules", "Schedules", "Interleave operations and test serializability", 12), ("snapshots", "Snapshots", "Choose a consistent visibility horizon", 10), ("tuple-versions", "Tuple versions", "Create and traverse version chains", 12), ("isolation", "Isolation levels", "Know what each level permits", 12), ("anomalies", "Anomalies", "Detect skew, phantoms, and lost updates", 12), ("vacuum", "Vacuum", "Reclaim versions without breaking readers", 10), ("mvcc-checkpoint", "Checkpoint", "Reason across concurrent timelines", 12)]),
    ("concurrency", "Concurrency control", "Coordinate conflicting work without stopping the world.", "⚭", [("latches-locks", "Latches vs locks", "Protect memory and logical data", 10), ("two-phase-locking", "Two-phase locking", "Build serializable schedules", 12), ("intention-locks", "Intention locks", "Coordinate multiple granularities", 10), ("deadlocks", "Deadlocks", "Detect cycles and choose victims", 12), ("optimistic", "Optimistic control", "Validate instead of block", 10), ("ssi", "Serializable snapshots", "Track dangerous structures", 12), ("hot-spots", "Hot spots", "Scale contended records", 10), ("concurrency-checkpoint", "Checkpoint", "Control competing transactions", 12)]),
    ("recovery", "Durability & recovery", "Make committed data survive power loss.", "↺", [("wal", "Write-ahead logging", "Order data and log persistence", 12), ("log-records", "Log records", "Describe physical and logical changes", 10), ("checkpoints", "Checkpoints", "Bound recovery without stopping work", 10), ("aries-analysis", "ARIES: analysis", "Reconstruct crash-time state", 12), ("aries-redo", "ARIES: redo", "Repeat history safely", 12), ("aries-undo", "ARIES: undo", "Roll back losers with compensation", 12), ("torn-pages", "Torn pages", "Defend against partial writes", 10), ("recovery-lab", "Lab: Crash Console", "Recover a crashed database", 15), ("recovery-checkpoint", "Checkpoint", "Guarantee durable outcomes", 12)]),
    ("replication", "Replication & partitioning", "Keep copies useful and divide data safely.", "◇", [("replication-models", "Replication models", "Ship bytes, logs, or rows", 10), ("sync-async", "Sync vs async", "Choose latency and loss windows", 10), ("replica-lag", "Replica lag", "Reason about stale reads", 10), ("failover", "Failover", "Promote without forking history", 12), ("sharding", "Sharding", "Choose boundaries and routing", 12), ("rebalancing", "Rebalancing", "Move ownership online", 12), ("consistent-hashing", "Consistent hashing", "Limit movement as nodes change", 10), ("replication-checkpoint", "Checkpoint", "Operate partitioned copies", 12)]),
    ("distributed", "Distributed databases", "Reason about truth when machines disagree.", "✦", [("time-order", "Time & ordering", "Work without a perfect global clock", 10), ("consensus", "Consensus", "Agree despite failure", 12), ("raft", "Raft", "Elect leaders and replicate logs", 12), ("distributed-tx", "Distributed transactions", "Coordinate atomic work", 10), ("two-phase-commit", "Two-phase commit", "Prepare, decide, and block", 12), ("distributed-serial", "Global serializability", "Order transactions across shards", 12), ("cap-pacelc", "CAP & PACELC", "Make precise tradeoff statements", 10), ("consensus-lab", "Lab: Consensus Timeline", "Repair a partitioned cluster", 15), ("distributed-checkpoint", "Final checkpoint", "Design a database from first principles", 15)])
]

LESSON_CONTENT = {
"latency-ladder": {
 "eyebrow":"UNIT 1 · LESSON 1", "title":"The latency ladder", "description":"Build the instinct behind almost every database optimization.",
 "cards":[
  {"id":"l1-intro","type":"story","title":"Why databases feel like magic","body":"A query can touch millions of records and still answer quickly. The trick is not simply faster code. A database carefully controls where data lives and how often it must travel.","label":"THE BIG IDEA","accent":"Databases are designed around avoiding expensive trips down the memory hierarchy.","bullets":["Keep frequently used data close to the CPU","Move data in useful groups instead of byte by byte","Reuse work before paying its cost again"]},
  {"id":"l1-scale","type":"story","title":"One second, stretched into a century","body":"Computer latencies are hard to feel because every number looks tiny. So imagine one CPU cycle lasts one second. An L1 cache lookup takes a few seconds. RAM takes minutes. An SSD read can take days. A network request can take months.","label":"SCALED FOR HUMAN INTUITION","accent":"A small-looking latency gap becomes enormous when repeated millions of times.","ladder":[["CPU / L1","~1 ns","seconds"],["RAM","~100 ns","minutes"],["SSD read","~100 μs","days"],["Network round trip","~1 ms+","weeks or months"]]},
  {"id":"l1-wait","type":"story","title":"The CPU cannot wish data closer","body":"Before a CPU can filter a row, the row's bytes must reach it. If those bytes are on storage, the request crosses several layers and the CPU may have nothing useful to do for that query while it waits.","label":"THE COST IS MOVEMENT","accent":"Computation is often cheap. Moving data is often expensive.","bullets":["CPU registers and caches are fastest but tiny","RAM is larger but slower","Persistent storage is vast but much slower","Networks add distance, queues, and unpredictable delay"]},
  {"id":"l1-predict","type":"choice","prompt":"Put yourself in the CPU's shoes. Which operation usually makes you wait the longest?","options":["Read an L1 cache line","Read from RAM","Read a random SSD page","Add two integers"],"answer":2,"explanation":"A random SSD read crosses the storage interface and waits on the device. It is vastly slower than arithmetic, cache, or RAM."},
  {"id":"l1-gap","type":"story","title":"The ratio matters more than the benchmark","body":"Hardware changes, so exact latency tables become outdated. The durable idea is the order-of-magnitude gap. If RAM is roughly one thousand times faster than a storage read, avoiding one storage trip can pay for a great deal of in-memory work.","label":"ENGINEER'S RULE","accent":"Compare orders of magnitude, not memorized nanoseconds."},
  {"id":"l1-order","type":"order","prompt":"Order these from lowest to highest typical latency.","items":["Random SSD read","L1 cache access","Main-memory access","Same-region network round trip"],"answer":["L1 cache access","Main-memory access","Random SSD read","Same-region network round trip"],"explanation":"Exact numbers vary, but the scale gap is the key: cache, then RAM, then local storage, then a network round trip."},
  {"id":"l1-model","type":"story","title":"Four ways databases fight latency","body":"Database internals can look like a bag of unrelated mechanisms. Most of them are responses to the same latency ladder.","label":"ONE MOTIVE, MANY MECHANISMS","accent":"Avoid trips · Amortize trips · Predict trips · Perform trips together","bullets":["Buffer pools avoid storage by retaining pages in RAM","Pages amortize one I/O across many nearby rows","Indexes avoid reading pages that cannot contain the answer","Batching overlaps or combines many small waits"]},
  {"id":"l1-apply","type":"choice","prompt":"A query repeatedly reads the same 8 KB table page. Which mechanism most directly avoids another SSD read?","options":["A buffer pool","A write-ahead log","A transaction lock","A query parser"],"answer":0,"explanation":"The buffer pool retains recently used disk pages in memory, serving later reads at RAM latency."},
  {"id":"l1-repeat","type":"story","title":"Say the model back in plain language","body":"When a page remains in the buffer pool, a later query gets it from RAM instead of storage. The database has moved the operation upward on the ladder. This single idea will return in indexes, joins, logging, and query planning.","label":"CORE MODEL · REPEAT 1","accent":"Databases are designed around avoiding expensive trips down the memory hierarchy."},
  {"id":"l1-math","type":"number","prompt":"A storage read takes 100 μs and a RAM access takes 0.1 μs. Approximately how many times slower is storage?","answer":1000,"tolerance":0,"suffix":"×","explanation":"100 ÷ 0.1 = 1,000. Ratios—not memorized benchmark numbers—build the useful intuition."},
  {"id":"l1-locality","type":"story","title":"Make every expensive trip useful","body":"Avoiding I/O is ideal, but sometimes data must come from storage. A database then fetches a whole page containing nearby rows. If the workload needs those rows soon, one expensive trip serves many operations. That is spatial locality.","label":"WHEN A TRIP IS UNAVOIDABLE","accent":"Pay once. Use many times.","bullets":["Temporal locality: reuse data accessed recently","Spatial locality: use data stored near what you requested"]},
  {"id":"l1-finish","type":"choice","prompt":"Which design best exploits spatial locality?","options":["Fetch one byte per storage request","Store related rows together in pages","Flush after every CPU instruction","Send every comparison over the network"],"answer":1,"explanation":"Grouping related rows makes one page read useful for many nearby accesses."},
  {"id":"l1-transfer","type":"choice","prompt":"An index lets a query skip 9,990 of 10,000 table pages. Which core principle explains the speedup?","options":["It makes SQL parsing free","It avoids expensive trips down the memory hierarchy","It guarantees every row is in CPU cache","It removes transaction isolation"],"answer":1,"explanation":"The index's main win is not faster comparison—it prevents thousands of storage or buffer-pool page visits."},
  {"id":"l1-anchor","type":"story","title":"The lens for the rest of this course","body":"Whenever you meet a database mechanism, ask three questions: What expensive movement does it avoid? What work does it group together? What locality does it exploit? Those questions turn implementation details into a coherent system.","label":"CORE MODEL · REPEAT 2","accent":"Databases are designed around avoiding expensive trips down the memory hierarchy.","bullets":["Avoid the trip","Make the trip carry more useful data","Reuse the result of the trip"]}
 ]
},
"pages-and-blocks": {
 "eyebrow":"UNIT 1 · LESSON 2", "title":"Pages & blocks", "description":"Understand the unit databases actually read, cache, lock, and flush.",
 "cards":[
  {"id":"p-intro","type":"story","title":"The row is not the I/O unit","body":"Storage devices transfer blocks, and databases organize data into fixed-size pages—commonly 4–16 KB. Asking for one row normally brings its entire page into memory.","accent":"one row → one page read"},
  {"id":"p-choice","type":"choice","prompt":"Why not make every database page exactly one row?","options":["SQL forbids it","Rows cannot contain text","It would waste locality and multiply I/O bookkeeping","Indexes require 8 KB rows"],"answer":2,"explanation":"Pages amortize transfer and metadata costs and capture spatial locality across many records."},
  {"id":"p-capacity","type":"number","prompt":"Ignoring headers, how many 128-byte rows fit in an 8 KB (8192-byte) page?","answer":64,"tolerance":0,"suffix":" rows","explanation":"8192 ÷ 128 = 64. Real pages hold fewer because headers and slot entries consume space."},
  {"id":"p-order","type":"order","prompt":"Order the read path from persistent data to the query operator.","items":["Operator consumes tuple","Storage returns page","Buffer pool chooses a frame","Page parser locates row"],"answer":["Buffer pool chooses a frame","Storage returns page","Page parser locates row","Operator consumes tuple"],"explanation":"The buffer manager provides memory, storage fills it, page code finds the record, and execution consumes it."},
  {"id":"p-final","type":"choice","prompt":"A page size increase most directly creates which tradeoff?","options":["More useful sequential data per I/O, but more read amplification for tiny random lookups","Stronger transaction isolation","Fewer SQL syntax errors","Automatic index compression"],"answer":0,"explanation":"Larger pages improve transfer efficiency and fanout but can fetch more irrelevant bytes for sparse random access."}
 ]
}
}

def public_card(card):
    return {k: v for k, v in card.items() if k not in ("answer", "tolerance")}

def find_lesson(slug):
    for ui, unit in enumerate(UNITS):
        for li, lesson in enumerate(unit[4]):
            if lesson[0] == slug:
                return ui, li, lesson
    return None
