import {useEffect,useState} from 'react';
import type {CSSProperties,ReactNode} from 'react';
import {Activity,BarChart3,BookOpen,ChevronRight,Database,Flame,Heart,Home,Layers3,LockKeyhole,Play,RotateCcw,Sparkles,Star,Trophy,X,Check,ArrowLeft} from 'lucide-react';
import {api} from './api';
import type {Card,Course,Lesson,Session,Unit} from './types';

type Page='home'|'learn'|'progress';
const iconMap=[Database,Layers3,Activity,Play,BarChart3,RotateCcw,LockKeyhole,BookOpen,Sparkles,Trophy];

function App(){
 const [page,setPage]=useState<Page>('home'),[data,setData]=useState<Course|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[session,setSession]=useState<Session|null>(null);
 const load=()=>{setLoading(true);setError('');api.dashboard().then(setData).catch(e=>setError(e.message)).finally(()=>setLoading(false))};
 useEffect(load,[]);
 if(session)return <LessonPlayer initial={session} onExit={()=>{setSession(null);load()}}/>;
 const begin=async(slug:string)=>{try{setSession(await api.start(slug))}catch(e){setError((e as Error).message)}};
 if(loading)return <div className="center-state"><div className="logo-mark"><Database/></div><div className="loader"/><p>Opening the workshop…</p></div>;
 if(error&&!data)return <div className="center-state"><h1>We couldn't reach the workshop</h1><p>{error}</p><button className="primary" onClick={load}>Try again</button></div>;
 return <div className="shell">
  <aside className="sidebar"><button className="brand" onClick={()=>setPage('home')}><span className="logo-mark"><Database/></span><span>PageCraft</span></button>
   <nav aria-label="Main navigation"><Nav active={page==='home'} icon={<Home/>} label="Home" onClick={()=>setPage('home')}/><Nav active={page==='learn'} icon={<Layers3/>} label="Learn" onClick={()=>setPage('learn')}/><Nav active={page==='progress'} icon={<BarChart3/>} label="Progress" onClick={()=>setPage('progress')}/></nav>
   <div className="sidebar-foot"><div className="mini-avatar">DB</div><div><strong>{data?.learner.name}</strong><small>Systems explorer</small></div></div>
  </aside>
  <main>{error&&<div className="toast">{error}<button onClick={()=>setError('')}><X size={16}/></button></div>}{page==='home'&&data&&<HomePage data={data} begin={begin} goLearn={()=>setPage('learn')}/>} {page==='learn'&&data&&<LearnPage data={data} begin={begin}/>} {page==='progress'&&data&&<ProgressPage data={data}/>}</main>
  <MobileNav page={page} setPage={setPage}/>
 </div>
}

function Nav({active,icon,label,onClick}:{active:boolean,icon:ReactNode,label:string,onClick:()=>void}){return <button className={active?'nav active':'nav'} onClick={onClick}>{icon}<span>{label}</span></button>}

function TopStats({data}:{data:Course}){return <div className="top-stats"><div title="Current streak"><Flame/> <b>{data.learner.streak}</b></div><div title="Total XP"><Star/> <b>{data.learner.xp}</b></div><div className="avatar">DB</div></div>}

function HomePage({data,begin,goLearn}:{data:Course,begin:(s:string)=>void,goLearn:()=>void}){
 const next=data.units.flatMap(u=>u.lessons).find(l=>l.slug===data.nextLesson); const unit=data.units.find(u=>u.lessons.some(l=>l.slug===data.nextLesson))||data.units[0];
 return <div className="page"><header><div><span className="kicker">YOUR WORKSHOP</span><h1>Ready to go deeper?</h1><p className="lede">Build the mental models behind the databases you use every day.</p></div><TopStats data={data}/></header>
 <section className="hero-card"><div className="hero-copy"><span className="pill">CONTINUE LEARNING</span><h2>{next?.title||'Course complete'}</h2><p>{next?.summary||'You have completed every available lesson.'}</p><div className="hero-meta"><span>Unit {unit.number} · {unit.title}</span><span>~{next?.minutes||0} min</span></div><button className="light-button" disabled={!next} onClick={()=>next&&begin(next.slug)}><Play size={18} fill="currentColor"/> Continue lesson</button></div><PageVisual/></section>
 <div className="section-head"><div><span className="kicker">TODAY</span><h2>Keep your momentum</h2></div><button className="text-button" onClick={goLearn}>View course <ChevronRight/></button></div>
 <div className="metric-grid"><Metric icon={<Flame/>} title="Daily goal" value={`${Math.min(data.learner.xp,data.learner.dailyGoal)} / ${data.learner.dailyGoal} XP`} color="orange" progress={Math.min(100,data.learner.xp/data.learner.dailyGoal*100)}/><Metric icon={<Trophy/>} title="Lessons complete" value={`${data.stats?.completed||0}`} color="green"/><Metric icon={<Activity/>} title="Answer accuracy" value={`${data.stats?.accuracy||0}%`} color="purple"/></div>
 <section className="unit-preview"><div className="unit-title"><div className="unit-icon"><Database/></div><div><span className="kicker">CURRENT UNIT</span><h2>{unit.title}</h2><p>{unit.description}</p></div><div className="unit-count">{unit.completed}/{unit.total}</div></div><div className="lesson-list">{unit.lessons.slice(0,4).map((lesson,i)=><LessonRow key={lesson.slug} lesson={lesson} index={i} begin={begin}/>)}</div></section>
 </div>
}

function PageVisual(){return <div className="page-visual" aria-hidden="true"><div className="page-header"><span/><span/><span/></div>{[0,1,2,3].map(i=><div className={`record r${i}`} key={i}><b>{i+1}</b><span/><span/></div>)}<div className="pointer p1"/><div className="pointer p2"/></div>}
function Metric({icon,title,value,color,progress}:{icon:ReactNode,title:string,value:string,color:string,progress?:number}){return <div className="metric"><div className={`metric-icon ${color}`}>{icon}</div><div className="metric-copy"><small>{title}</small><strong>{value}</strong>{progress!==undefined&&<div className="small-progress"><i style={{width:`${progress}%`}}/></div>}</div></div>}

function LessonRow({lesson,index,begin}:{lesson:Lesson,index:number,begin:(s:string)=>void}){const locked=lesson.status==='locked'||!lesson.playable;return <button className="lesson-row" disabled={locked} onClick={()=>begin(lesson.slug)}><span className={`lesson-number ${lesson.status}`}>{lesson.status==='completed'?<Check/>:locked?<LockKeyhole/>:index+1}</span><span className="lesson-info"><strong>{lesson.title}</strong><small>{lesson.summary}</small></span><span className="lesson-time">{lesson.playable?`${lesson.minutes} min`:'Coming soon'}</span><ChevronRight/></button>}

function LearnPage({data,begin}:{data:Course,begin:(s:string)=>void}){return <div className="page learn-page"><header><div><span className="kicker">DATABASE INTERNALS</span><h1>Your learning path</h1><p className="lede">10 units · 70+ lessons · beginner foundations to distributed systems</p></div><TopStats data={data}/></header><div className="course-map">{data.units.map((unit,i)=><UnitBlock key={unit.slug} unit={unit} icon={iconMap[i]} begin={begin}/>)}</div></div>}
function UnitBlock({unit,icon:Icon,begin}:{unit:Unit,icon:typeof Database,begin:(s:string)=>void}){const [open,setOpen]=useState(unit.number===1);const pct=Math.round(unit.completed/unit.total*100);return <section className={`unit-block ${unit.number>1?'future':''}`}><button className="unit-banner" onClick={()=>setOpen(!open)}><span className="unit-badge"><Icon/></span><span className="unit-banner-copy"><small>UNIT {unit.number}</small><strong>{unit.title}</strong><em>{unit.description}</em></span><span className="ring" style={{'--progress':`${pct*3.6}deg`} as CSSProperties}><b>{pct}%</b></span><ChevronRight className={open?'rotate':''}/></button>{open&&<div className="unit-lessons">{unit.lessons.map((l,i)=><LessonRow key={l.slug} lesson={l} index={i} begin={begin}/>)}</div>}</section>}

function ProgressPage({data}:{data:Course}){return <div className="page"><header><div><span className="kicker">YOUR PROGRESS</span><h1>Systems fluency, measured</h1><p className="lede">A clear view of practice, precision, and course mastery.</p></div><TopStats data={data}/></header><div className="progress-hero"><div><small>TOTAL EXPERIENCE</small><strong>{data.learner.xp}</strong><span>XP earned</span></div><div className="big-streak"><Flame/><strong>{data.learner.streak}</strong><span>day streak</span></div></div><div className="metric-grid"><Metric icon={<BookOpen/>} title="Lessons completed" value={`${data.stats?.completed||0}`} color="green"/><Metric icon={<Activity/>} title="Accuracy" value={`${data.stats?.accuracy||0}%`} color="purple"/><Metric icon={<RotateCcw/>} title="Skills to review" value={`${data.stats?.review||0}`} color="orange"/></div><section className="mastery"><h2>Course mastery</h2>{data.units.map(u=><div className="mastery-row" key={u.slug}><span>Unit {u.number}</span><strong>{u.title}</strong><div className="mastery-bar"><i style={{width:`${u.completed/u.total*100}%`}}/></div><b>{u.completed}/{u.total}</b></div>)}</section></div>}

function MobileNav({page,setPage}:{page:Page,setPage:(p:Page)=>void}){return <nav className="mobile-nav"><Nav active={page==='home'} icon={<Home/>} label="Home" onClick={()=>setPage('home')}/><Nav active={page==='learn'} icon={<Layers3/>} label="Learn" onClick={()=>setPage('learn')}/><Nav active={page==='progress'} icon={<BarChart3/>} label="Progress" onClick={()=>setPage('progress')}/></nav>}

function LessonPlayer({initial,onExit}:{initial:Session,onExit:()=>void}){
 const [session,setSession]=useState(initial),[selected,setSelected]=useState<unknown>(null),[feedback,setFeedback]=useState<{correct:boolean,explanation:string}|null>(null),[busy,setBusy]=useState(false),[done,setDone]=useState<any>(null);
 const card=session.card; const progress=session.position/session.total*100;
 const submit=async()=>{if(selected===null&&card.type!=='story')return;setBusy(true);try{const r=await api.answer(session.id,card.type==='story'?'continue':selected);setFeedback(r);setSession(s=>({...s,hearts:r.hearts??s.hearts,xpEarned:s.xpEarned+(r.xpAwarded||0)}))}finally{setBusy(false)}};
 const next=async()=>{if(feedback&&!feedback.correct){setFeedback(null);return}setBusy(true);try{const r=await api.advance(session.id);if(r.completed)setDone(r);else{setSession(r);setSelected(null);setFeedback(null)}}finally{setBusy(false)}};
 if(done)return <div className="lesson-shell completion"><div className="completion-burst"><Trophy/></div><span className="kicker">LESSON COMPLETE</span><h1>{done.perfect?'Flawless work!':'Mental model upgraded!'}</h1><p>You turned a database mechanism into working intuition.</p><div className="reward-grid"><div><Star/><strong>{done.xpEarned}</strong><span>XP earned</span></div><div><Activity/><strong>{done.score}%</strong><span>accuracy</span></div><div><Flame/><strong>{done.streak}</strong><span>day streak</span></div></div><button className="primary" onClick={onExit}>Back to your path</button></div>;
 return <div className="lesson-shell"><div className="lesson-top"><button className="icon-button" onClick={onExit} aria-label="Exit lesson"><X/></button><div className="lesson-progress"><i style={{width:`${progress}%`}}/></div><div className="hearts"><Heart fill="currentColor"/> {session.hearts}</div></div><div className="lesson-stage"><span className="kicker">{session.lesson.eyebrow}</span><h1>{card.prompt||card.title}</h1>{card.type==='story'&&<Story card={card}/>} {card.type==='choice'&&<Choices card={card} selected={selected} setSelected={setSelected} feedback={feedback}/>} {card.type==='order'&&<Order card={card} selected={selected} setSelected={setSelected} feedback={feedback}/>} {card.type==='number'&&<NumberAnswer card={card} selected={selected} setSelected={setSelected} feedback={feedback}/>}</div><div className={`lesson-footer ${feedback?(feedback.correct?'correct':'incorrect'):''}`}>{feedback?<div className="feedback"><span className="feedback-icon">{feedback.correct?<Check/>:<X/>}</span><div><strong>{feedback.correct?'Exactly right':'Not quite yet'}</strong><p>{feedback.explanation}</p></div></div>:<div/>}<button className={feedback?'primary':'check-button'} disabled={busy||(card.type!=='story'&&selected===null)} onClick={feedback?next:submit}>{busy?'Checking…':feedback?(feedback.correct?'Continue':'Try again'):(card.type==='story'?'Got it':'Check answer')}</button></div></div>
}
function Story({card}:{card:Card}){return <div className="theory-card"><div className="theory-heading"><div className="theory-icon"><Database/></div><span>{card.label||'MENTAL MODEL'}</span></div><p>{card.body}</p>{card.ladder&&<div className="latency-ladder">{card.ladder.map((row,i)=><div key={row[0]}><i>{i+1}</i><strong>{row[0]}</strong><span>{row[1]}</span><em>{row[2]}</em></div>)}</div>}{card.bullets&&<ul>{card.bullets.map(item=><li key={item}><Check/>{item}</li>)}</ul>}<div className="accent-note">{card.accent}</div></div>}
function Choices({card,selected,setSelected,feedback}:{card:Card,selected:unknown,setSelected:(v:unknown)=>void,feedback:any}){return <div className="choices">{card.options?.map((o,i)=><button key={o} disabled={!!feedback} className={selected===i?'choice selected':'choice'} onClick={()=>setSelected(i)}><span>{String.fromCharCode(65+i)}</span>{o}</button>)}</div>}
function Order({card,selected,setSelected,feedback}:{card:Card,selected:any,setSelected:(v:unknown)=>void,feedback:any}){const values=Array.isArray(selected)?selected:[];const remaining=card.items?.filter(x=>!values.includes(x))||[];return <div className="order"><p className="hint">Tap items in order. Tap a placed item to undo.</p><div className="order-slots">{Array.from({length:card.items?.length||0}).map((_,i)=><button key={i} className={values[i]?'filled':''} disabled={!values[i]||!!feedback} onClick={()=>setSelected(values.slice(0,i))}>{values[i]||`${i+1}`}</button>)}</div><div className="order-bank">{remaining.map(x=><button key={x} disabled={!!feedback} onClick={()=>setSelected([...values,x])}>{x}</button>)}</div></div>}
function NumberAnswer({card,selected,setSelected,feedback}:{card:Card,selected:unknown,setSelected:(v:unknown)=>void,feedback:any}){return <div className="number-answer"><label><span>Your estimate</span><div><input autoFocus type="number" disabled={!!feedback} value={(selected as string)||''} onChange={e=>setSelected(e.target.value)}/><b>{card.suffix}</b></div></label></div>}
export default App;
